### PR TITLE
Two new functions, variants of dir->angles and angles->dir 

### PR DESCRIPTION
**Pull request by ABOS80**

### CODE REVIEW

**Comment by AlexKnauth** [comment]
Why do the changes look this big?

**Comment by ABOS80** [comment]
I don't know, it's my first pull request. ;-)

**Comment by ABOS80** [comment]
First I added the functions then the lines under "provide". Might be the problem.

**Comment by AlexKnauth** [comment]
I tried re-commiting the changes on my own branch and now the diff looks normal:
https://github.com/AlexKnauth/pict3d/commit/4d23c1bd86d2f92501443a4f5a78f06a5af02b00

I don't know why git's diffs were doing that before. Should we put that commit onto your PR branch?

**Comment by ABOS80** [comment]
PR branch?

**Comment by AlexKnauth** [comment]
For this pull request it's your `master` branch, but for most pull requests it should be a different branch.

**Comment by ABOS80** [comment]
Well I whanted it to be included in the main one.

**Comment by jeapostrophe** [comment]
Yes, we want it to be on the master one when it gets merged here, but on yours, we want to see the smallest set of changes. I don't really understand why it looks like this though. Can you try it again?

**Comment by AlexKnauth** [comment]
If you want I can try pushing my re-commited commit onto @APOS80's master.

**Comment by ABOS80** [comment]
I think the problem is that two commits is pushed at once. @AlexKnauth, please try. I will push the scribble next, I just have to write it.

**Comment by AlexKnauth** [comment]
Okay, done. The diff looks normal now.

**Comment by ABOS80** [comment]
Nice, I'm going to look at a git tutorial now. ;-)

**Comment by jeapostrophe** [comment]
Now that I can see the changes more clearly, I think there's a bit too much duplication in them... is there a way to abstract it a bit?

**Comment by AlexKnauth** [comment]
It might be possible to use dir values `+z`, `+y`, etc. instead of symbols for the axes, and then you could do the same math for all of them...

**Comment by ABOS80** [comment]
I'm open to suggestions.

**Comment by ABOS80** [comment]
Well, even though I would like it to be smaller I can't see a better way.

**Comment by AlexKnauth** [comment]
I tried implementing a version of `angles->dir-yp` by transforming the dir given by `angles->dir`, but it ended up returning very different results from your current implementation, so I'm not sure I understand what a different set of axes means for this function. Could you give some examples of what you would use it for and what you would expect?

**Comment by ABOS80** [comment]
The present function has a weird point of origin, yaw around z starting at x. The view coordinate system is -y up and -z from you and the world has a reversed z axis. Yaw around z might had been enuf but why not give people more options,

**Comment by jeapostrophe** [comment]
I was thinking something like this

```
;; XXX define Axis type

(: angles->dir-yp (-> Real Real Axis Dir))
(define (angles->dir-yp ang1 ang2 axis)
  (define ang1 (fl (degrees->radians ang1)))
  (define ang2 (fl (degrees->radians ang2)))
  (define ca1 (flcos ang1))
  (define sa1 (flsin ang1))
  (define ca2 (flcos ang2))
  (define sa2 (flsin ang2))
  (cond
    ;Yaw around Z axis
    [(equal? 'zx axis) (dir (fl*  1.0 (fl* ca1 ca2)) (fl* 1.0 (fl* sa1 ca2)) (fl* -1.0 sa2))] ;Yaw from x, Pitch counterclockwise.
    [(equal? 'zy axis) (dir (fl* -1.0 (fl* sa1 ca2)) (fl* 1.0 (fl* ca1 ca2)) (fl*  1.0 sa2))] ;Yaw from y, Pitch counterclockwise.
    ;Yaw around Y axis
    [(equal? 'yz axis) (dir (fl*  1.0 (fl* sa1 ca2)) (fl* -1.0 sa2) (fl*  1.0 (fl* ca1 ca2)))] ;Yaw from z, Pitch counterclockwise.
    [(equal? 'yx axis) (dir (fl*  1.0 (fl* ca1 ca2)) (fl*  1.0 sa2) (fl* -1.0 (fl* sa1 ca2)))] ;Yaw from x, Pitch counterclockwise.
    ; Yaw around X axis
    [(equal? 'xy axis) (dir (fl* -1.0 sa2) (fl*  1.0 (fl* ca1 ca2)) (fl*  1.0 (fl* sa1 ca2)))] ;Yaw from y, Pitch counterclockwise.
    [(equal? 'xz axis) (dir (fl*  1.0 sa2) (fl* -1.0 (fl* sa1 ca2)) (fl*  1.0 (fl* ca1 ca2)))] ;Yaw from z, Pitch counterclockwise.
    [else (dir 0.0 0.0 0.0)]))


(: dir->angles-yp (-> Dir Axis (List Flonum Flonum)))
(define (dir->angles-yp dv axis)
  (define x (fl (dir-dx dv)))
  (define y (fl (dir-dy dv)))
  (define z (fl (dir-dz dv)))
  (define r (flsqrt (fl+ (fl* x x) (fl+ (fl* y y) (fl* z z)))))

  ;; Axis of yaw
  (define a
    (case axis
      [(zx zy) z]
      [(yz yx) y]
      [(xy xz) x]))

  (define-values (fst snd)
    (case axis
      [(zx) (values y x)]
      [(zy) (values x y)]
      [(yz) (values x z)]
      [(yx) (values z x)]
      [(xy) (values z y)]
      [(xz) (values y z)]))

  ;; Pitch is counter-clockwise
  (list (radians->degrees (atan fst snd))
        (radians->degrees (asin (fl/ a r)))))
```

**Comment by ABOS80** [comment]
This doesn't really matter anymore, I solved it all with quaternions. No gimbal-lock and works well.

**Pull request closed without merging**
